### ISSUE TITLE
关于论文似乎有一处引用错误

### ISSUE THREAD

**Issue by Jinxuepeng123** [millieXie/FusionMamba#1]
(ES2D) [7]这里的[7]应该是[15]

**Comment by millieXie** [comment]
感谢提醒。
后面会修改的。




谢小笙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "millieXie/FusionMamba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 下午4:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[millieXie/FusionMamba] 关于论文似乎有一处引用错误 (Issue #1)





 
(ES2D) [7]这里的[7]应该是[15]
