### ISSUE TITLE
作者您好，我想知道怎么让最后的融合图像保持原先的尺寸

### ISSUE THREAD

**Issue by JoyTsing** [millieXie/FusionMamba#16]
我在融合的时候注意到融合后的图像会变成256x256，该如何保持融合前的尺寸

**Comment by JoyTsing** [comment]
如果只是单纯修改test中的resize会存在不匹配的问题

**Comment by millieXie** [comment]
你把代码里面的resize改成融合之前的size是可以，没什么问题，性能上可能稍微会有一点不太一样。 用后面的那个代码转换也可以。

**Comment by JoyTsing** [comment]
> 你把代码里面的resize改成融合之前的size是可以，没什么问题，性能上可能稍微会有一点不太一样。 用后面的那个代码转换也可以。

好的，非常感谢，我之前是把test里的resize给直接注释掉，想请问一下具体修改是需要怎么做？

**Comment by millieXie** [comment]
可以直接注释掉，也可以resize的时候直接改成输入的resize，也可以用里面那个changesize那个文件来改，都可以 想怎么做都行
